version: "3.9"
services:
  klipper:
    build: ./klipper
    image: saxmfone1/klipper:${TAG:-latest}
    volumes:
      - /dev:/dev
      - ./klipstack/log:/var/log
      - ./klipstack/sdcard:/sdcard
      - ./klipstack/tmp:/tmp
      - ./klipstack/conf:/home/klippy/.config
    device_cgroup_rules:
      - 'c 166:* rmw'
      - 'c 81:* rmw'
    user: "${USER_ID}"
    hostname: klipper.local
    restart: unless-stopped
  moonraker:
    build: ./moonraker
    image: saxmfone1/moonraker:${TAG:-latest}
    volumes:
      - ./klipstack/log:/var/log
      - ./klipstack/sdcard:/sdcard
      - ./klipstack/tmp:/tmp
      - ./klipstack/conf:/home/moonraker/.config
    user: "${USER_ID}"
    hostname: moonraker.local
    ports:
      - 7125:7125
    restart: unless-stopped
  fluidd:
    image: saxmfone1/fluidd:${TAG:-latest}
    hostname: fluidd.local
    ports:
      - 8081:80
    restart: unless-stopped
networks:
  default:
    name: klipper
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/26
