version: "3.9"
services:
  klipper:
    build: ./klipper
    image: saxmfone1/klipper
    volumes:
      - /dev:/dev
      - ./klipstack/log:/var/log
      - ./klipstack/sdcard:/home/klippy/sdcard
      - ./klipstack/tmp:/tmp
      - ./klipstack/conf/klipper:/home/klippy/.config
    device_cgroup_rules:
      - 'c 166:* rmw'
      - 'c 81:* rmw'
    user: "${UID}"
    hostname: klipper.local
    restart: unless-stopped
  moonraker:
    build: ./moonraker
    image: saxmfone1/moonraker
    volumes:
      - ./klipstack/log:/var/log
      - ./klipstack/sdcard:/home/moonraker/sdcard
      - ./klipstack/tmp:/tmp
      - ./klipstack/conf/moonraker:/home/moonraker/moonraker
    user: "${UID}"
    hostname: moonraker.local
    ports:
      - 7125:7125
    restart: unless-stopped
  fluidd:
    image: saxmfone1/fluidd
    hostname: fluidd.local
    ports:
      - 8081:80
    restart: unless-stopped
networks:
  default:
    name: klipper
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/26
